#!/bin/sh
#$ -S /bin/bash
#$ -cwd
#$ -soft -l ljob,lmem
#$ -l s_vmem=16G
#$ -l mem_req=16
cuffnorm -p 8 --total-hits-norm -o ./cuffnorm_out_BRIC-seq_HeLa_ver2_RefSeq /home/akimitsu/Refseq_gene_hg19_June_02_2014.gtf ./cuffquant_out_BRIC-seq_HeLa_ver2_0h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_1h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_1_5h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_2h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_3h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_4h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_5h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_6h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_8h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_10h_RefSeq/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_12h_RefSeq/abundances.cxb
cuffnorm -p 8 --total-hits-norm -o ./cuffnorm_out_BRIC-seq_HeLa_ver2_Gencode_v19 /home/akimitsu/gencode.v19.annotation.gtf ./cuffquant_out_BRIC-seq_HeLa_ver2_0h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_1h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_1_5h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_2h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_3h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_4h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_5h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_6h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_8h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_10h_Gencode_v19/abundances.cxb ./cuffquant_out_BRIC-seq_HeLa_ver2_12h_Gencode_v19/abundances.cxb
#cuffnorm -p 8 --total-hits-norm -o ./cuffnorm_out_BRIC-seq_HeLa_RefSeq /home/akimitsu/Refseq_gene_hg19_June_02_2014.gtf tophat_out_BRIC-seq_HeLa_ver2_0h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_1h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_1_5h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_2h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_3h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_4h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_5h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_6h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_8h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_10h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_12h/accepted_hits.bam
#cuffnorm -p 8 --total-hits-norm -o ./cuffnorm_out_BRIC-seq_HeLa_Gencode_v19 /home/akimitsu/gencode.v19.annotation.gtf tophat_out_BRIC-seq_HeLa_ver2_0h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_1h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_1_5h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_2h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_3h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_4h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_5h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_6h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_8h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_10h/accepted_hits.bam tophat_out_BRIC-seq_HeLa_ver2_12h/accepted_hits.bam
